apiVersion: v1
kind: Service
metadata:
# this is the hostname of the service by which it can be accessed over HTTP.
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
